image: node:10

cache:
  paths:
  - node_modules/

before_script:
  - whoami
  - node --version
  - npm install

stages:
- tag
- release

Tag:
  tags:
    - infrastructure
  stage: tag
  only:
    - master
  script:
    - GL_TOKEN=$GL_TOKEN npx semantic-release

Release:
  stage: release
  tags:
    - infrastructure
  script:
    - CTX=dev CTX_NO=1 make release
  only:
    - tags

Deploy-to-Production:
  stage: release
  environment:
    name: production
  tags:
    - infrastructure
  when: manual
  script:
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_ID"
    - git remote set-url origin "https://$CI_USERNAME:$CI_ACCESS_TOKEN@gitlab.com/bluedotio/backend_ui/wave_demo.git"
    - git config --get remote.origin.url
    - git remote show origin
    - git fetch
    - git checkout production
    - git reset --hard origin/production
    - git merge $CI_BUILD_REF
    - git push origin production
  only:
    - tags
  
Production:
  stage: release
  environment:
    name: production
  tags:
    - infrastructure
  script:
    - CTX=prod CTX_NO=1 make release
  only:
    - production

